//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FY111.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayAttributeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayAttributeResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FY111.Resources.DisplayAttributeResources", typeof(DisplayAttributeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 應用程式 的當地語系化字串。
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 頭像 的當地語系化字串。
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否開啟報到 的當地語系化字串。
        /// </summary>
        public static string CheckinEnabled {
            get {
                return ResourceManager.GetString("CheckinEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查點Id 的當地語系化字串。
        /// </summary>
        public static string CkptId {
            get {
                return ResourceManager.GetString("CkptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單元名稱 的當地語系化字串。
        /// </summary>
        public static string ClassLittleUnitName {
            get {
                return ResourceManager.GetString("ClassLittleUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 教室名稱 的當地語系化字串。
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課程單元Id 的當地語系化字串。
        /// </summary>
        public static string ClassUnitId {
            get {
                return ResourceManager.GetString("ClassUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課程名稱 的當地語系化字串。
        /// </summary>
        public static string ClassUnitName {
            get {
                return ResourceManager.GetString("ClassUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代碼 的當地語系化字串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內容 的當地語系化字串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前密碼 的當地語系化字串。
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 裝置名稱 的當地語系化字串。
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課程時長 的當地語系化字串。
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email 的當地語系化字串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間 的當地語系化字串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖標 的當地語系化字串。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片 的當地語系化字串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否報名 的當地語系化字串。
        /// </summary>
        public static string isSignedUp {
            get {
                return ResourceManager.GetString("isSignedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新的Email 的當地語系化字串。
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼 的當地語系化字串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認新密碼 的當地語系化字串。
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所屬組織 的當地語系化字串。
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通過 的當地語系化字串。
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認密碼 的當地語系化字串。
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話號碼 的當地語系化字串。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 記得我? 的當地語系化字串。
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色 的當地語系化字串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分數 的當地語系化字串。
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否開啟報名 的當地語系化字串。
        /// </summary>
        public static string SignupEnabled {
            get {
                return ResourceManager.GetString("SignupEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始時間 的當地語系化字串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者名稱 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
