-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 11:48:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fy111
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fy111
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fy111` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fy111` ;

-- -----------------------------------------------------
-- Table `fy111`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `icon` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`login_log` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Device_type` INT NOT NULL,
  `start_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Member_id`, `start_time`),
  INDEX `fk_Login_Log_Device1_idx` (`Device_type` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Log_Device1`
    FOREIGN KEY (`Device_type`)
    REFERENCES `fy111`.`device` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`Class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `ip` CHAR(15) NOT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `signup_enabled` TINYINT NOT NULL DEFAULT '0',
  `checkin_enabled` TINYINT NOT NULL DEFAULT '0',
  `duration` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`class_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`class_log` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Class_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NULL DEFAULT NULL,
  `score` INT NULL,
  PRIMARY KEY (`Member_id`, `start_time`),
  INDEX `fk_Metaverse_Log_Metaverse1_idx` (`Class_id` ASC) VISIBLE,
  CONSTRAINT `fk_Metaverse_Log_Metaverse1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `fy111`.`Class` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`class_signup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`class_signup` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Class_id` INT NOT NULL,
  PRIMARY KEY (`Member_id`, `Class_id`),
  INDEX `fk_Metaverse_has_Member_Metaverse2_idx` (`Class_id` ASC) VISIBLE,
  CONSTRAINT `fk_Metaverse_has_Member_Metaverse2`
    FOREIGN KEY (`Class_id`)
    REFERENCES `fy111`.`Class` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`class_checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`class_checkin` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Class_id` INT NOT NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Member_id`, `Class_id`),
  INDEX `fk_Metaverse_has_Member_Metaverse1_idx` (`Class_id` ASC) VISIBLE,
  CONSTRAINT `fk_Metaverse_has_Member_Metaverse1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `fy111`.`Class` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`Class_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`Class_unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Class_id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Class_id`),
  CONSTRAINT `fk_class_unit_class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `fy111`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fy111`.`class_littleunit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`class_littleunit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Class_unit_id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Class_unit_id`),
  CONSTRAINT `fk_class_littleunit_class_unit1`
    FOREIGN KEY (`Class_unit_id`)
    REFERENCES `fy111`.`Class_unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fy111`.`Class_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`Class_question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Class_id` INT NOT NULL,
  `discription` VARCHAR(100) NULL,
  `option` TEXT NULL,
  PRIMARY KEY (`id`, `Class_id`),
  CONSTRAINT `fk_class_question_class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `fy111`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
