-- MySQL Script generated by MySQL Workbench
-- Tue May  3 14:49:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fy111
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fy111
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fy111` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fy111` ;

-- -----------------------------------------------------
-- Table `fy111`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `icon` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`login_log` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Device_type` INT NOT NULL,
  `start_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Member_id`, `start_time`),
  INDEX `fk_Login_Log_Device1_idx` (`Device_type` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Log_Device1`
    FOREIGN KEY (`Device_type`)
    REFERENCES `fy111`.`device` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`metaverse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`metaverse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `ip` CHAR(15) NOT NULL,
  `icon` VARCHAR(45) NULL DEFAULT NULL,
  `introduction` TEXT NULL DEFAULT NULL,
  `signup_enabled` TINYINT NOT NULL DEFAULT '0',
  `checkin_enabled` TINYINT NOT NULL DEFAULT '0',
  `duration` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`metaverse_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`metaverse_log` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Metaverse_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Member_id`, `start_time`),
  INDEX `fk_Metaverse_Log_Metaverse1_idx` (`Metaverse_id` ASC) VISIBLE,
  CONSTRAINT `fk_Metaverse_Log_Metaverse1`
    FOREIGN KEY (`Metaverse_id`)
    REFERENCES `fy111`.`metaverse` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`metaverse_signup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`metaverse_signup` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Metaverse_id` INT NOT NULL,
  PRIMARY KEY (`Member_id`, `Metaverse_id`),
  INDEX `fk_Metaverse_has_Member_Metaverse2_idx` (`Metaverse_id` ASC) VISIBLE,
  CONSTRAINT `fk_Metaverse_has_Member_Metaverse2`
    FOREIGN KEY (`Metaverse_id`)
    REFERENCES `fy111`.`metaverse` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fy111`.`metaverse_checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fy111`.`metaverse_checkin` (
  `Member_id` VARCHAR(256) NOT NULL,
  `Metaverse_id` INT NOT NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Member_id`, `Metaverse_id`),
  INDEX `fk_Metaverse_has_Member_Metaverse1_idx` (`Metaverse_id` ASC) VISIBLE,
  CONSTRAINT `fk_Metaverse_has_Member_Metaverse1`
    FOREIGN KEY (`Metaverse_id`)
    REFERENCES `fy111`.`metaverse` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `FY111`.`Device`
-- -----------------------------------------------------
START TRANSACTION;
USE `FY111`;
INSERT INTO `FY111`.`Device` (`id`, `icon`, `name`) VALUES (DEFAULT, NULL, 'PC');
INSERT INTO `FY111`.`Device` (`id`, `icon`, `name`) VALUES (DEFAULT, NULL, 'Phone');
INSERT INTO `FY111`.`Device` (`id`, `icon`, `name`) VALUES (DEFAULT, NULL, 'AR');
INSERT INTO `FY111`.`Device` (`id`, `icon`, `name`) VALUES (DEFAULT, NULL, 'VR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `FY111`.`Metaverse`
-- -----------------------------------------------------
START TRANSACTION;
USE `FY111`;
INSERT INTO `FY111`.`Metaverse` (`id`, `name`, `ip`, `icon`, `introduction`, `signup_enabled`, `checkin_enabled`, `duration`) VALUES (DEFAULT, '工廠', '1.1.1.1', NULL, NULL, 1, 1, 120);
INSERT INTO `FY111`.`Metaverse` (`id`, `name`, `ip`, `icon`, `introduction`, `signup_enabled`, `checkin_enabled`, `duration`) VALUES (DEFAULT, '手術', '2.2.2.2', NULL, NULL, 1, 0, 240);
INSERT INTO `FY111`.`Metaverse` (`id`, `name`, `ip`, `icon`, `introduction`, `signup_enabled`, `checkin_enabled`, `duration`) VALUES (DEFAULT, '會議', '3.3.3.3', NULL, NULL, 1, 1, 90);
INSERT INTO `FY111`.`Metaverse` (`id`, `name`, `ip`, `icon`, `introduction`, `signup_enabled`, `checkin_enabled`, `duration`) VALUES (DEFAULT, '教室', '4.4.4.4', NULL, NULL, 1, 0, 90);

COMMIT;